### ISSUE TITLE
JSON response: camelCase vs  field_name

### ISSUE THREAD

**Issue by steverawlins-zebra** [zalopay-oss/jmeter-grpc-request#100]
Which is it supposed to be:

myField

my_field

?

I just re-installed my jMeter and gRPC plug-in and it seems to have changed.

Running jMeter 5.4.3
/usr/local/Cellar/jmeter/5.4.3/libexec/lib/ext with plugin:

21490900 Jan 28 10:59 jmeter-grpc-request-v1.2.1.jar

**Comment by yl-yue** [comment]
If the problem has been solved, please close the issue, thank you!

**Comment by steverawlins-zebra** [comment]
It is not clear to me how this change in behavior happened.  We were using JSON syntax in our Assert/BoundaryExtractors, but when we upgrade zalopay grpc request plug-in, the responses changed to grpc_convention.  Was this an intentional change to bring the zalopay plug-in back to the Google naming convention.

**Comment by yl-yue** [comment]
> 请问你的意思是，响应结果被自动驼峰转换了么。如果是这样的，那这应该是grpc客户端行为，jmeter是java客户端，因此会自动遵守驼峰命名规约。
> 但这应该不会阻碍到你对JMeter的使用，如果是命名规范的问题，恕我暂时无能为力。

Do you mean that the response was humped automatically? If so, this should be GRPC client behavior, and JMeter is a Java client, so it automatically complies with the hump naming convention.
However, this should not hinder your use of JMeter. If it is a naming convention problem, I can do nothing about it.

https://developers.google.cn/protocol-buffers/docs/style#message_and_field_names

**Comment by steverawlins-zebra** [comment]
I am referring to the response payload, not Java code.  I noticed that the field names in the gRPC response changed when I upgrade this plug-in.

**Comment by yl-yue** [comment]
Do you have any specific screenshots or examples

**Comment by steverawlins-zebra** [comment]
I have reproduced the issue by downgrading to the grpc plugin v1.1.1

**Comment by yl-yue** [comment]
Is the result correct in V1.2.1? If not, what do you expect in V1.2.1?
My expected results:
```
...
```
Actual results:
```
...
```

**Comment by steverawlins-zebra** [comment]
it's OK the way it is in v1.2.1 using google_my_field

Please do not flip it back to camelCase (because we have to change our Assertions/Boundary Extractor each time it changes)

**Comment by yl-yue** [comment]
I can understand that I don't need to provide a 'PR' for this requirement right?
Because of this problem, it has been solved in 'V1.2.1'.

Or I need to provide a function switch like Camel Case and Snake Case conversion for this requirement

**Comment by steverawlins-zebra** [comment]
You do not, in my opinion, need a PR to change anything.  Please leave the response syntax as it is now, in V1.2.1

field_name_snake_case
