### ISSUE TITLE
How do I add metadata for TLS verification

### ISSUE THREAD

**Issue by julialoh** [zalopay-oss/jmeter-grpc-request#115]
Hello, I'm trying to connect to a server that requires TLS certification. I've converted my certs/private key to a pks12 file but am unsure how to pass it as metadata. I get the following error: 
`2022-05-02 15:26:53,808 ERROR v.z.b.c.m.Writer: UNAVAILABLE: io exception`
Any idea why? And what to do to fix this?

**Comment by steverawlins-zebra** [comment]
Authorization Header Bearer Token.

`grpcurl -H "Authorization: Bearer xxx"`

But how can you be sure that the test is not working?  Maybe your service itself is broken. 

> UNAVAILABLE | 14 | The service is currently unavailable. This is most likely a transient condition, which can be corrected by retrying with a backoff. Note that it is not always safe to retry non-idempotent operations.




UNAVAILABLE | 14 | The service is currently unavailable. This is most likely a transient condition, which can be corrected by retrying with a backoff. Note that it is not always safe to retry non-idempotent operations.
-- | -- | --

**Comment by julialoh** [comment]
I do need to check if the ip is correct since i'm getting the unavailable error, but I think there's also an issue with my token. Sorry if this question is stupid, I'm a bit new but how do I generate the xxx part of the token? I have a .p12 file but am unsure how to format it to pass as "Authorization: Bearer xxx".
