### ISSUE TITLE
Use Variables in Metadata

### ISSUE THREAD

**Issue by NateTsg** [zalopay-oss/jmeter-grpc-request#12]
Hey,

I was trying to set access token dynamically in the metadata but it just sends the variable name as a string.

Regards

**Comment by Karthicsrv** [comment]
Yes we are also facing the same issue

**Comment by NateTsg** [comment]
@Karthicsrv you can use property values to set the metadata dynamically

**Comment by blindchaser** [comment]
When I tried to add Metadata, I got: 
Response code: 500
Response message: Exception: UNKNOWN

I'm not sure if I put the wrong format, do you have a working example for metadata here? thx

**Comment by huynhminhtan** [comment]
Hi @blindchaser,

You can try again with format `key1:value1,key2:value2` of metadata.
Everything will be fine.

**Comment by vidyabhushan40** [comment]
HI @huynhminhtan 
I am also facing issue with metadata, I have already tried with several format but still it is not working and shows issue 

**Response code: 500
Response message: Exception: UNKNOWN**

Below format I have tried with but none of them works for me. Please share format with example

 authorization : h7Zd4eIXQ/BKiL9v5M/aY4JFfPp
"authorization" : "h7Zd4eIXQ/BKiL9v5M/aY4JFfPp"
{"authorization" : "h7Zd4eIXQ/BKiL9v5M/aY4JFfPp"}

**Comment by Ankit7327** [comment]
Hi @NateTsg @huynhminhtan 

I am trying to pass variable value in GRPC metadata from CSV but its passing  like **${varibaleName}**.  Its not replacing the string with actual value in csv.
Can you please provide your input on this

**Comment by NateTsg** [comment]
@Ankit7327 I couldn't pass the variable it doesn't replace the variable .I used property in the form of 

access_token:${__groovy(props.get("token_" + ${__threadNum}))} 

I iterate through the CSV and store it on the props using props.set("key", "value") then retrieve the value as shown above

**Comment by Ankit7327** [comment]
@NateTsg I tried as you suggested but its partially working in my case. 
I am able to replace values in meta data but if I execute it for multiple iteration it takes the same value. Values in metadata not changing as per the thread
Can you please share any snippet or code for storing values in pros by iterating csv?

**Comment by NateTsg** [comment]
store each variable with a separate thread key as follows so when you read the variable you get a different one for each thread

props.put("token_"+Thread.currentThread().getName().split("-")[1],vars.get("token"));

I store it on the props with a different thread number and get it with the thread number in the following code 
access_token:${_groovy(props.get("token" + ${__threadNum}))}

**Comment by Ankit7327** [comment]
@NateTsg which sampler you have used?

**Comment by Ankit7327** [comment]
@NateTsg @huynhminhtan 
Query 1:-
I tried above solution, it worked properly with single iteration but while executing under load jmeter replacing blank values in parameter. Have you face this issue?
Query2:-
I tried to execute multiple request at a time. When I click on play button green dot appeared on upper right corner but users were not ramping up. There is only 1 second of ramp up is defined and test was schedule for 15 min.

Please help on this

**Comment by fronojono** [comment]
@vidyabhushan40 

You can fix it with 

Authorization:Bearer USER_TOKEN
