### ISSUE TITLE
不支持mac m1芯片

### ISSUE THREAD

**Issue by aisuosuo** [zalopay-oss/jmeter-grpc-request#149]

**Comment by minhhoangvn** [comment]
You can work around it by inputting the java properties "-Dos.arch=x86_64" since the library of protoc did not have an executable for M1 with arm chipset.

**Comment by aisuosuo** [comment]
> You can work around it by inputting the java properties "-Dos.arch=x86_64" since the library of protoc did not have an executable for M1 with arm chipset.

How to do this step, can you show it in pictures?

**Comment by minhhoangvn** [comment]
![image](https://user-images.githubusercontent.com/17515250/179757304-66772a04-d409-406c-af5f-f29727ab72d7.png)
Edit both files with the content below in the last line
![image](https://user-images.githubusercontent.com/17515250/179757538-50380cd9-71d7-4d88-8f38-de6c2e8028dd.png)

**Comment by aisuosuo** [comment]
This problem has been solved，thanks
