### ISSUE TITLE
Calling proto without package is not working

### ISSUE THREAD

**Issue by leanalcabasa** [zalopay-oss/jmeter-grpc-request#180]
Hello,

Is there a way to call grpc endpoints without the package name?

We have a few and it was not working. When I tried to add a package and specified it in the Full Method, it works.

Is there a default package to put or what should I place in the Full Method for packagename?

packagename.servicename/methodname

**Comment by Amoratinos** [comment]
Hi! I'm about to open a PR to solve this issue. 

AFAIK, package names are optional in the specification and with few changes the plugin can support services with or without packages.
