### ISSUE TITLE
gRPC - Library Directory (optional) 

### ISSUE THREAD

**Issue by Karthicsrv** [zalopay-oss/jmeter-grpc-request#19]
Could you pls share the gRPC-Library Directory  --> Default files.

Thanks,
SRV

**Comment by huynhminhtan** [comment]
Hi @Karthicsrv ,
Can you please tell me what Default files you want?

**Comment by Karthicsrv** [comment]
Can you pls elaborate how to map & identify the field mask related proto files with the grpc sampler in optional - LIB folder place.

Tried multiple ways but the field mask related gRPC calls are not working.

When I executing the gRPC field mask related sampler, noticed few file automatically generating in the below path. Executed with these generated files while mapping in the LIB folder, butting getting errors.![Uploading 98975986...]

C:\\users\administrators\appdata\local\temp\2\polyglot-well-know-typesxxxxxxx\google\protobuf\*.protos

**Comment by lujingshidiyi** [comment]
https://github.com/googleapis/googleapis
Download ZIP
