### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to read messages from json

### ISSUE THREAD

**Issue by krzysztofkobrenczuk** [zalopay-oss/jmeter-grpc-request#20]
Hello. 

I was trying to send request with json. Empty json: {} is working correct, but when I'm trying to send something more I received error on readWithJsonData() method - line 99  jsonParser.merge(jsonData, nextMessage);

![image](https://user-images.githubusercontent.com/24368029/99249944-32628200-280b-11eb-97c9-d723a66ee88f.png)

**Comment by huynhminhtan** [comment]
Hi @krzysztofkobrenczuk,

I think the JSON format of the request is wrong, please check it again.
Can you attach the proto file that you are using?

More example: [here](https://github.com/zalopay-oss/jmeter-grpc-request/tree/master/dist/example)

_JSON format:_ _Bookstore/CreateShelf_
```json
{
  "shelf": {
    "id": 1234567,
    "theme": "Hello server!!"
  }
}
```

For proto file:

```proto
service Bookstore {
  rpc CreateShelf (CreateShelfRequest) returns (Shelf) {
    option (google.api.http) = {
      post: "/v1/shelves"
      body: "shelf"
    };
  }
}

message CreateShelfRequest {
  Shelf shelf = 1;
}

// A shelf resource.
message Shelf {
  // A unique shelf id.
  int64 id = 1;
  // A theme of the shelf (fiction, poetry, etc).
  string theme = 2;
}
```

**Comment by krzysztofkobrenczuk** [comment]
@huynhminhtan Thank you for that fast response!
Unfortunately I'm not allowed to attach proto file, but using BloomRPC everything is working as expected. Request is the same as I'm trying to use in Jmeter. In BloomRPC i received response on many streams. 

1 case: i had empty request {} for ping-pong service and it passed perfectly.
2 case: had request which is working in BloomRPC but when I'm trying to send it by Jmeter - that error occurs and server is not getting any hit, View Results Tree is empty and logs appear in console. 

![image](https://user-images.githubusercontent.com/24368029/99254576-da2f7e00-2812-11eb-9b10-9ad98a66cbc5.png)

**Comment by huynhminhtan** [comment]
Hi @krzysztofkobrenczuk,

The error logs appear in console, I think there's a problem with the parsing request message step. Would you be able to check the data type for each field again?

You can change `cutoff_timestamp` to `cutoffTimestamp`, this might work fine. Also, please make sure to import external packages like Google APIs if you use one (more https://github.com/zalopay-oss/jmeter-grpc-request/issues/1).

Uhm... Are you using streaming? It looks like that. Unfortunately, the _jmeter-grpc-request_ currently supports Unary RPCs of service method, you can see details [DynamicGrpcClient.java#L29](https://github.com/zalopay-oss/jmeter-grpc-request/blob/master/src/main/java/vn/zalopay/benchmark/core/grpc/DynamicGrpcClient.java#L29). But, the error occurs in parsing step.
 
I hope everything will be all right.
