### ISSUE TITLE
Variable values not getting replaced in Metadata filed of GRPC request

### ISSUE THREAD

**Issue by Ankit7327** [zalopay-oss/jmeter-grpc-request#26]
Hi @NateTsg @huynhminhtan

I am trying to pass variable value in GRPC metadata from CSV but its passing like ${varibaleName}. Its not replacing the string with actual value in csv.
Can you please provide your input on this

**Comment by femassa1** [comment]
Hi @michael-azran, the field "Metadata" don't read variables.

if anyone knows how to send variables i would appreciate it.
