### ISSUE TITLE
run the sample using Basic authentication

### ISSUE THREAD

**Issue by michael-azran** [zalopay-oss/jmeter-grpc-request#31]
i am trying to run the plugin with basic authentication after encoding base64 user:token and getting errors
i am sending metadata as
Authorization: Basic ${TOKEN_AFTER_BASE64}
and i am getting the below
what am i missing?

DATA-----------------------------
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>openresty/1.15.8.2</center>
</body>
</html>
",Thread Group - GetContent 1-1,text,false,,38,0,1,1,null,0,0,0
1616406042986,2,GRPC GetContentVersion Incremental List Request,500,"Exception: UNAUTHENTICATED: HTTP status code 401
invalid content-type: text/html
headers: Metadata(:status=401,server=openresty/1.15.8.2,date=Mon, 22 Mar 2021 09:40:42 GMT,content-type=text/html,content-length=185,strict-transport-security=max-age=15724800; includeSubDomains,www-authenticate=Basic realm=""Authentication Required - Test"")

**Comment by femassa1** [comment]
Hi @michael-azran, the field "Metadata" don't read variables.

if anyone knows how to send variables i would appreciate it.
