### ISSUE TITLE
Error: Could not find or load main class server.BookStoreServer.

### ISSUE THREAD

**Issue by debayandesarkar** [zalopay-oss/jmeter-grpc-request#36]
Hi,
I am getting the below exception starting the gRPC server. Can you please help?

-rw-rw-r--@ 1  1668562246  31906745 Apr  4 00:22 gprc-server-1.0-SNAPSHOT.jar
➜  dist java -cp "./gprc-server-1.0-SNAPSHOT.jar" server.BookStoreServer.
Error: Could not find or load main class server.BookStoreServer.
Caused by: java.lang.ClassNotFoundException: server.BookStoreServer.

Regards
Debayan

**Comment by huynhminhtan** [comment]
Hi @debayandesarkar, 

Could you please pull the latest source code or release? checking java environment then try again. I still run successfully.

Regards

![image](https://user-images.githubusercontent.com/15891411/121769104-f2d6fb00-cb8b-11eb-9149-59691d198b69.png)

**Comment by huynhminhtan** [comment]
Hi @debayandesarkar,

I will close the issue as obsolete. For simplicity, you can run the example here [#running-the-examples](https://github.com/zalopay-oss/jmeter-grpc-request#running-the-examples) at the latest release. You can reopen the case again should there still be any issues.

I hope everything will be all right.
Regards
