### ISSUE TITLE
Publish to jmeter-plugin so can be directly downloaded from jmeter plugins manager UI

### ISSUE THREAD

**Issue by dhartford** [zalopay-oss/jmeter-grpc-request#38]
This is up to the authors, but I think it would greatly increase visibility and presence if this was visible within the mainstream jmeter plugin manager download option. Currently there are no GRPC plugins, and most external plugins maintain author/etc but are added through jmeter-plugins.org

some potential steps here, most reference reviewing the group threads for the steps: https://groups.google.com/g/jmeter-plugins/c/be-vMCfPA_g/m/x4dvAq24AAAJ

Recommend updating license information, such as to pom.xml.
example: https://github.com/undera/jmeter-plugins/blob/master/plugins/perfmon/pom.xml

**Comment by huynhminhtan** [comment]
Hi @dhartford, thanks for your suggestion,

The JMeter gRPC Request was published at JMeter Plugins Manager by merge request [jmeter-plugins/pull/458](https://github.com/undera/jmeter-plugins/pull/458). So,
we can find here https://jmeter-plugins.org/?search=jmeter-grpc-request
