### ISSUE TITLE
Option to disable SSL/TLS Cert verification

### ISSUE THREAD

**Issue by dhartford** [zalopay-oss/jmeter-grpc-request#44]
Add ability to disable SSL/TLS cert verification please

**Comment by huynhminhtan** [comment]
Hi @dhartford,

Thanks for the PR, I'm sorry for the late answer.
Overall view, this looks ok to me but there are some minor GUI layout issues that can be fixed later.

GUI updated:
![image](https://user-images.githubusercontent.com/15891411/120068971-8947ee80-c0ad-11eb-8762-624dcf69cf4d.png)


Thank you
