### ISSUE TITLE
gRPC request cut JSON fields with emty values

### ISSUE THREAD

**Issue by spakhom** [zalopay-oss/jmeter-grpc-request#59]
Hello!
Trying to use gRPC plugin for some perfomance testing on our server.
I'm trying to send some JSON with several fields for request e.g. :
{
"filterByStatus": [],
"totalsByStatus": [],
"date": "2021-07-28T00:00:00.000Z",
"offset": 0,
"limit": 12,
"sortBy": "",
"sortDirectionDesc": false,
"vName": "",
...
"lName": ""
}
this is general request to get everything for current date.
So, i've added View Results Tree sampler for debug and it show me request body as:
{
"date": "2021-07-28T00:00:00Z",
"limit": 12
}

I need send all fields, because in over case server just returns me OK. 200. instead of data set.

Could you please help me solve this problem ?

**Comment by skarpushin** [comment]
I've created a pull request to address this: https://github.com/zalopay-oss/jmeter-grpc-request/pull/61
