### ISSUE TITLE
Allow relative paths to Proto Root and Libraries directories

### ISSUE THREAD

**Issue by nmelnic** [zalopay-oss/jmeter-grpc-request#71]
Currently it is not possible to set relative path to Proto Root and Libraries directories like ./protofiles/projectX

**Comment by yl-yue** [comment]
Proto Root Directory will soon support `${}` resolution, see [pr#85](https://github.com/zalopay-oss/jmeter-grpc-request/pull/85)

Can it meet this demand

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
