### ISSUE TITLE
Modifying User-Agent

### ISSUE THREAD

**Issue by singhyadvendra** [zalopay-oss/jmeter-grpc-request#9]
Hi,

I am trying to pass User-agent in metadata section but it is not working.

Thanks
Yadvendra

**Comment by huynhminhtan** [comment]
Hi @singhyadvendra,

Please try again with the Metadata entry which must be defined in `key1:value1,key2:value2`.

See more: [ClientCaller.java#L76](https://github.com/zalopay-oss/jmeter-grpc-request/blob/master/src/main/java/vn/zalopay/benchmark/core/ClientCaller.java#L76)
