### ISSUE TITLE
Allow plugin to clean the temp folder which uses to store the proto code generation files after finishing a test

### ISSUE THREAD

**Issue by minhhoangvn** [zalopay-oss/jmeter-grpc-request#94]
Allow plugin to clean the temp folder which uses to store the proto code generation files after finishing a test. This will help the load generator machine can free the disk after running the performance test.

**Comment by yl-yue** [comment]
> 这个功能貌似应该是jmeter本身的能力，而非jmeter-grpc-request需要提供，jmeter-grpc-request运行过程中不会生成临时文件
This seems to be the capability of JMeter itself, Instead of jmeter-grpc-Request, Jmeter-grpc-request runs without generating temporary files

**Comment by minhhoangvn** [comment]
Currently, the core gRPC protoc library will generate the code in the temporary folder, you can get the file in  the /tmp folder which include a bunch of descriptor5759582146797680044.pb.bin and polyglot-well-known-types folder, it will consume a computer disk and need a process to clean that data after completing the performance test
https://github.com/zalopay-oss/jmeter-grpc-request/blob/787b4ef5bd355336cd8849583ce8e536a7992f16/src/main/java/vn/zalopay/benchmark/core/protobuf/ProtocInvoker.java#L83

**Comment by yl-yue** [comment]
Thank you, this problem does exist, we should produce and sell ourselves
